version: '3.8'

services:
  webapi:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: src/api/WebApi/Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      JwtSettings__Issuer: Chrono-Master.WebApi
      JwtSettings__Audience: Chrono-Master.Client
      JwtSettings__ExpirationInDays: 5
      JwtSettings__SecretKey: my_super_secret_key_for_jwt_production
      AdminSettings__Id: 72207f4c-b389-4f60-8ba0-fe526940e585
      AdminSettings__Password: strong_pa55w0rD
      ConnectionStrings__Postgresql: User Id=postgres;Password=postgres;Server=postgres_db;Port=5432;Database=Sms;IntegratedSecurity=true;Pooling=true;

  postgres_db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5433
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
