version: '3.8'

services:
  webapi:
    image: djoufson/webapi
    depends_on:
      - database
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      JwtSettings__Issuer: Chrono-Master.WebApi
      JwtSettings__Audience: Chrono-Master.Client
      JwtSettings__ExpirationInDays: 5
      JwtSettings__SecretKey: my_super_secret_key_for_jwt_production
      AdminSettings__Id: 72207f4c-b389-4f60-8ba0-fe526940e585
      AdminSettings__Password: strong_pa55w0rD
      ConnectionStrings__Postgresql: User Id=postgres;Password=postgres;Server=database;Port=5432;Database=Sms;IntegratedSecurity=true;Pooling=true;

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5433
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
  client:
    image: djoufson/client
    depends_on:
      - webapi
    ports:
      - "8080:3000"

volumes:
  postgresdata:
